version: "2.4"

volumes:
    elastic:

services:
    mancala-fe:
        image: nginx
        ports:
            - "80:80"
        links:
            - fluentbit-fe
        depends_on:
          - fluentbit-fe
          - mancala-be
        volumes:
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./mancalaGame-mancala/mancalaFrontend:/usr/share/nginx/html
        logging:
            driver: "fluentd"
            options:
                fluentd-address: localhost:51101
                tag: fe.app.aybuke

    mancala-be:
        image: unlenen/mancala:1.0
        ports:
            - "8080:8080"
        links:
            - fluentbit-be
        depends_on:
          - fluentbit-be
        logging:
            driver: "fluentd"
            options:
                fluentd-address: localhost:51102
                tag: be.app.aybuke

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
        restart: on-failure
        mem_limit: 2g
        environment:
          - discovery.type=single-node
        ports:
          - 9200:9200
        volumes:
          - elastic:/usr/share/elasticsearch/data
        networks:
          - local
        depends_on:
          - fluentbit-efk
        logging:
          driver: fluentd
          options:
            fluentd-address: localhost:51103
            tag: efk.aybuke

    kibana:
        image: docker.elastic.co/kibana/kibana-oss:7.10.2
        restart: on-failure
        mem_limit: 256m
        environment:
          - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        ports:
          - 5601:5601
        networks:
          - local
        depends_on:
          - fluentbit-efk
          - elasticsearch
        logging:
          driver: fluentd
          options:
            fluentd-address: localhost:51103
            tag: kibana.aybuke

    fluentbit-fe:
        image: fluent/fluent-bit:1.8
        command:
          - /fluent-bit/bin/fluent-bit
          - --config=/etc/fluent-bit/fluent-bit.conf
        environment:
          - FLB_ES_HOST=elasticsearch
          - FLB_ES_PORT=9200
        ports:
          - 51101:24224

        volumes:
          - ./conf/:/etc/fluent-bit/:ro
        networks:
          - local

    fluentbit-be:
        image: fluent/fluent-bit:1.8
        command:
          - /fluent-bit/bin/fluent-bit
          - --config=/etc/fluent-bit/fluent-bit.conf
        environment:
          - FLB_ES_HOST=elasticsearch
          - FLB_ES_PORT=9200
        ports:
          - 51102:24224
        volumes:
          - ./conf/:/etc/fluent-bit/:ro
        networks:
          - local

    fluentbit-efk:
        image: fluent/fluent-bit:1.8
        command:
          - /fluent-bit/bin/fluent-bit
          - --config=/etc/fluent-bit/fluent-bit.conf
        environment:
          - FLB_ES_HOST=elasticsearch
          - FLB_ES_PORT=9200
        ports:
          - 51103:24224
        volumes:
          - ./conf/:/etc/fluent-bit/:ro
        networks:
          - local
        
networks:
  local:
    driver: bridge

