{
 "title": "Host Resource Usage Example",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without(cpu) (irate(node_cpu_seconds_total{job=\"prometheus\",instance=\"192.168.231.233:9100\", mode!=\"idle\"}[1m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.231.233:9100\",job=\"prometheus\"} - node_memory_MemFree_bytes{instance=\"192.168.231.233:9100\",job=\"prometheus\"} - node_memory_Cached_bytes{job=\"prometheus\",instance=\"192.168.231.233:9100\"} - node_memory_Buffers_bytes{instance=\"192.168.231.233:9100\",job=\"prometheus\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"192.168.231.233:9100\",job=\"prometheus\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"192.168.231.233:9100\",job=\"prometheus\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"192.168.231.233:9100\",job=\"prometheus\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"prometheus\",instance=\"192.168.231.233:9100\",device!~\"/dev/loop.*\", device!~\"tmpfs|nsfs\", device!=\"gvfsd-fuse\"} - node_filesystem_avail_bytes{job=\"prometheus\",instance=\"192.168.231.233:9100\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Available ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=\"prometheus\",instance=\"192.168.231.233:9100\",device!~\"/dev/loop.*\",device!~\"tmpfs|nsfs\",device!=\"gvfsd-fuse\"} \n\n",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"prometheus\",instance=\"192.168.231.233:9100\"}[5m])",
     "legendFormat": "{{device}} receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"prometheus\",instance=\"192.168.231.233:9100\"}[5m])",
     "legendFormat": "{{device}} transmit "
    }
   ]
  }
 ]
}